### ISSUE TITLE
Ad failed to load with error code 0(internal Error)

### ISSUE THREAD

**Issue by Syedwaheed** [HMS-Core/hms-ads-demo-kotlin#1]
Hey @chenqiuwei I m getting the above error continuously in demo Application. I have HMS core Version 6.0.1.305. My internet connection is stable. I m just stuck in it. Even though I have created my own test application on app gallery that has been approved but still safe error. No luck yet. Can you please help me into it.
Following is the code for my test application. I m using Android studio Arctic Fox 2020.3.1

Module.gradle

plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id 'com.huawei.agconnect'
}

android {
    compileSdk 30

    defaultConfig {
        applicationId "com.example.huaweitestads"
        minSdk 21
        targetSdk 30
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
}

dependencies {

    implementation 'androidx.core:core-ktx:1.6.0'
    implementation 'androidx.appcompat:appcompat:1.3.1'
    implementation 'com.google.android.material:material:1.4.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.0'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.3'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'

    //Huawei Dependency
    implementation 'com.huawei.agconnect:agconnect-core:1.5.2.300'
    implementation 'com.huawei.hms:ads-lite:13.4.45.308'

    implementation 'com.huawei.hms:ads-identifier:3.4.34.301'
}
Project.gradle

// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        google()
        jcenter()
        maven {url 'https://developer.huawei.com/repo/'}
    }
    dependencies {
        classpath "com.android.tools.build:gradle:7.0.0"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.21"
        classpath 'com.huawei.agconnect:agcp:1.6.0.300'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

setting.gradle
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        jcenter() // Warning: this repository is going to shut down soon
        maven {url 'https://developer.huawei.com/repo/'}
    }
}
rootProject.name = "HuaweiTestAds"
include ':app'

class MainActivity : AppCompatActivity() {
    private val adListener: AdListener = object : AdListener(){
        override fun onAdClosed() {
            showToast("Ad closed")
        }

        override fun onAdFailed(p0: Int) {
            showToast(String.format(Locale.ROOT, "Ad failed to load with error code %d.", p0))
        }

        override fun onAdLeave() {
            showToast("Ad Leave")
        }

        override fun onAdOpened() {
            showToast(String.format("Ad opened "))
        }

        override fun onAdLoaded() {
            showToast("Ad loaded.")
        }

        override fun onAdClicked() {
            showToast("Ad clicked")
        }

        override fun onAdImpression() {
            showToast("Ad Impression")
        }
    }
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        //initialize the Huawei Ads
        HwAds.init(this)

        val bannerView: BannerView? = findViewById(R.id.hw_banner_view)
        bannerView!!.adListener = adListener
        bannerView.setBannerRefresh(30)
        val adParam = AdParam.Builder().build()
        bannerView.loadAd(adParam)
    }
    private fun showToast(message: String) {
        Toast.makeText(this, message, Toast.LENGTH_SHORT).show()
    }
}
below is activity.xml
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:hwads="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/cl_root_view"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".MainActivity">

 
    <TextView
        android:id="@+id/textView"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:text="hello "
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" />

    <com.huawei.hms.ads.banner.BannerView
        android:id="@+id/hw_banner_view"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@id/textView"
        hwads:adId="testw6vs28auh3"
        hwads:bannerSize="BANNER_SIZE_320_50" />

</androidx.constraintlayout.widget.ConstraintLayout>

**Comment by Mike-mei** [comment]
Can you provide the full log？

**Comment by Syedwaheed** [comment]
@Mike-mei 
![huawei-ad-error](https://user-images.githubusercontent.com/14071753/130439465-b86ffccb-696d-465e-a7c0-110d5a853df8.png)

**Comment by Mike-mei** [comment]
In order to locate your issue quickly, please run the following command to obtain full logs:

1. adb logcat -v time >d:/hwads.txt
2. Reproduce the problem scenario.
3. Press Ctrl + C and copy the log to here

**Comment by Syedwaheed** [comment]
![logcat-error](https://user-images.githubusercontent.com/14071753/130951777-92ac43df-e112-4a9a-b9d6-0885f19e50a7.png)
Preview window is not showing up if you have the banner or native tag ad. Exception is viewing in the above images.

Following is the logcat file please review:
[hwads.txt](https://github.com/HMS-Core/hms-ads-demo-kotlin/files/7057211/hwads.txt)

**Comment by Mike-mei** [comment]
Please check whether the network is connected to the U.S.
The conditions for test ID request to Ads：
1. HUAWEI Phones outside China.
2. In the network where HMS service can be provided (non-US).
3. Synchronize the mobile phone time with the current time.
4. The HMS version is the latest
5. The phone is not inserted into a SIM card in China or the US.

**Comment by Syedwaheed** [comment]
All conditions are met but still Ads aren't running. Guess what it is running on samsung device S7 and showing error on huawei y6

**Comment by Syedwaheed** [comment]
I have inserted the SIM Card in Huawei Phone and the Ads are showing perfectly fine on huawei and other phones too.

**Comment by 329937626** [comment]
> I have inserted the SIM Card in Huawei Phone and the Ads are showing perfectly fine on huawei and other phones too.

How do you solve this problem?I meet the same problem.
